# Generated by Django 2.2.1 on 2019-12-10 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20191210_0843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Del',
        ),
    ]
