# Generated by Django 2.2.1 on 2019-12-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_delete_del'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
