# Generated by Django 2.2.1 on 2019-12-06 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. Must have at least 5 characters.', max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=5, message='Username must be at least 5 characters long.')], verbose_name='username'),
        ),
    ]
