# Generated by Django 2.2.1 on 2019-12-09 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191206_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. Must have at least 5 characters.', max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=5, message='Username must be at least 5 characters long.')], verbose_name='username'),
        ),
    ]
